Repository cognitedata/cognite-sdk-js, pull requests merged in 2021-06, with the labels that each got.

#541 feat(documents): [SBS-3442, SBS-3648] Endpoints for documents
  packages/beta/src/__tests__/api/documentsApi.int.spec.ts
  packages/beta/src/__tests__/api/documentsApi.unit.spec.ts
  packages/beta/src/__tests__/testUtils.ts
  packages/beta/src/api/documents/documentsApi.ts
  packages/beta/src/api/documents/feedbackApi.ts
  packages/beta/src/api/documents/pipelinesApi.ts
  packages/beta/src/cogniteClient.ts
  packages/beta/src/index.ts
  packages/beta/src/types.ts
Labels: auto-merge, auto-update

#567 feat: [SBS-3722] search by size range
  packages/beta/src/__tests__/api/documentsApi.int.spec.ts
  packages/beta/src/__tests__/api/documentsApi.unit.spec.ts
  packages/beta/src/types.ts
Labels: auto-merge, auto-update

#583 chore: release new version of wells [release]
  packages/wells/package.json
Labels: auto-merge

#584 chore: add grep as codeowners for /documents
  .github/CODEOWNERS
Labels: auto-merge

#579 feat: document preview endpoints [release]
  packages/beta/src/__tests__/api/documentsApi.int.spec.ts
  packages/beta/src/__tests__/api/documentsApi.unit.spec.ts
  packages/beta/src/api/documents/documentsApi.ts
  packages/beta/src/api/documents/previewApi.ts
  packages/beta/src/types.ts
Labels: auto-merge

#591 feat: added support for variables and operationName for templates
  packages/beta/src/__tests__/api/templateGraphQlApi.int.spec.ts
  packages/beta/src/api/templateGroups/templateGraphQlApi.ts
  packages/beta/src/cogniteClient.ts
Labels: auto-update

#590 feat: directoryPrefix filter for files [release]
  packages/stable/src/__tests__/api/files.int.spec.ts
  packages/stable/src/__tests__/api/files.unit.spec.ts
  packages/stable/src/__tests__/testUtils.ts
  packages/stable/src/types.ts
Labels: auto-merge
