Repository cognitedata/cognite-sdk-js, pull requests merged in 2021-08, with the labels that each got.

#635 fix(playground): wrong response type for documents search [release]
  packages/playground/src/__tests__/api/documentsApi.int.spec.ts
  packages/playground/src/api/documents/documentsApi.ts
  packages/playground/src/types.ts
Labels: auto-merge

#628 fix(core): remove slash suffix from uris [release]
  packages/core/src/httpClient/basicHttpClient.ts
  packages/core/src/httpClient/basicHttpClient.unit.spec.ts
Labels: auto-merge, auto-update

#625 test: do not run tests for irrelevant packages
  .github/workflows/tests.yaml
Labels: enhancement, auto-update

#614 feat(playground): add document feedback [release]
  packages/playground/src/__tests__/api/documentsApi.int.spec.ts
  packages/playground/src/__tests__/api/documentsApi.uint.spec.ts
  packages/playground/src/api/documents/documentsApi.ts
  packages/playground/src/api/documents/feedbackApi.ts
  packages/playground/src/types.ts
Labels: auto-update

#627 fix(core): headers set by the sdk must respect case insensitive keys
  packages/core/src/__tests__/httpClient/basicHttpClient.unit.spec.ts
  packages/core/src/httpClient/basicHttpClient.ts
  packages/core/src/index.ts
Labels: auto-update

#581 feat(templates): add lastCreatedTime and lastUpdatedTime
  packages/beta/src/__tests__/api/templateGroups.int.spec.ts
  packages/beta/src/__tests__/api/templateInstances.int.spec.ts
  packages/beta/src/api/templateGroups/templateInstancesApi.ts
  packages/beta/src/types.ts
Labels: auto-update

#640 fix(playground): incorrect GeoLocation definition [release]
  packages/playground/src/__tests__/api/documentsApi.uint.spec.ts
  packages/playground/src/types.ts
Labels: auto-update

#523 docs: fix documentation [skip ci]
  packages/beta/README.md
Labels: auto-merge

#634 feat: add update support template instances
  packages/beta/src/__tests__/api/templateInstances.int.spec.ts
  packages/beta/src/api/templateGroups/templateInstancesApi.ts
  packages/beta/src/types.ts
  packages/stable/src/types.ts
Labels: auto-update

#630 docs: await loginWithOAuth in code snippets
  packages/core/src/baseCogniteClient.ts
Labels: auto-update

#650 feat(playground): filter based on asset subtree [release]
  packages/playground/src/__tests__/api/documentsApi.uint.spec.ts
  packages/playground/src/types.ts
Labels: auto-update

#658 test: temporary skip for entityMatching
  packages/stable/src/__tests__/api/entityMatching.int.spec.ts
Labels: auto-merge

#657 fix(func-test): make function test more reliable
  packages/playground/src/__tests__/api/functionsApi.int.spec.ts
Labels: auto-merge, auto-update

#659 test: temporary skip assets mappings 3d
  packages/stable/src/__tests__/api/assetMappings3D.int.spec.ts
Labels: auto-merge, auto-update

#626 docs: update readme [skip-ci]
  README.md
Labels: auto-merge

#648 fix(playground): geo location filter
  packages/playground/src/__tests__/api/documentsApi.int.spec.ts
  packages/playground/src/types.ts
Labels: auto-merge, auto-update
