Repository cognitedata/cognite-sdk-js, pull requests merged in 2022-05, with the labels that each got.

#792 feat(documents): content and list endpoints + stricter types
  packages/stable/src/__tests__/api/documentsApi.int.spec.ts
  packages/stable/src/__tests__/api/documentsApi.unit.spec.ts
  packages/stable/src/api/documents/documentsApi.ts
  packages/stable/src/api/documents/previewApi.ts
  packages/stable/src/api/documents/types.gen.ts
Labels: auto-update

#805 fix(geospatial): change feature search stream response
  packages/stable/src/api/geospatial/featureAPI.ts
  packages/stable/src/api/geospatial/types.ts
Labels: auto-merge

#806 feat(annotations): support for suggest endpoint
  packages/playground/src/__tests__/api/annotationsApi.int.spec.ts
  packages/playground/src/api/annotations/annotationsApi.ts
  packages/playground/src/api/annotations/types.ts
Labels: auto-merge, auto-update

#809 fix(documents): label type in documents
  packages/stable/src/api/documents/types.gen.ts
Labels: auto-merge, auto-update
