Repository cognitedata/cognite-sdk-js, pull requests merged in 2023-01, with the labels that each got.

#933 fix(stable): document preview fields that were optional
  packages/stable/src/.cognite-openapi-snapshot.json
  packages/stable/src/api/documents/types.gen.ts
Labels: auto-merge

#898 chore(codegen): support ignore filter
  packages/codegen/src/__tests__/codegen.uint.spec.ts
  packages/codegen/src/codegen.ts
  packages/codegen/src/configuration.ts
  packages/codegen/src/generate.ts
Labels: auto-merge

#910 chore: fix typo
  packages/playground/README.md
Labels: auto-merge, auto-update

#942 test: update file id for the test file used by Vision
  packages/stable/src/__tests__/api/visionApi.int.spec.ts
Labels: auto-merge, auto-update

#940 chore(raw): tune raw rows insert chunk size 10k->5k
  packages/stable/src/api/raw/rawRowsApi.ts
Labels: auto-update

#939 feat: support names filter for 3D list nodes endpoint [release]
  packages/stable/src/__tests__/api/revisions3D.int.spec.ts
  packages/stable/src/types.ts
Labels: auto-update
